Repository fvwmorg/fvwm3, pull requests merged in 2020-12, with the labels that each got.

#317 FvwmEvent: remove support for Rplay
  bin/fvwm-config.in
  configure.ac
  doc/fvwm3/fvwm3.adoc
  doc/modules/FvwmEvent.adoc
  fvwm/fvwm3.c
  libs/Fplay.h
  libs/Makefile.am
  modules/FvwmAnimate/Makefile.am
  modules/FvwmEvent/FvwmEvent.c
  modules/FvwmEvent/Makefile.am
Labels: breaking

#318 CI: reduce IRC notification noise
  .github/workflows/ccpp.yml
Labels: development

#327 CI: add issues script
  .github/workflows/issues.yml
Labels: development

#339 Make bin/FvwmCommand.in use @PYTHON@
  bin/FvwmCommand.in
Labels: bug

#345 ewmhbasestruts: handle `0 0 0 0` when maximizing
  fvwm/ewmh.c
  fvwm/fvwm3.c
Labels: bug

#371 Github: add templates for PRs/issues
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: skip:changelog

#377 fix error in manpage name: fvwm-config-2.6 -> fvwm-convert-2.6
  doc/bin/fvwm-convert-2.6.adoc
Labels: area:build, area:doc, type:bug

#379 Remove FvwmConsoleC.pl front-end
  .gitignore
  configure.ac
  doc/modules/FvwmConsole.adoc
  doc/modules/FvwmConsoleC.pl.adoc
  modules/FvwmConsole/.fvwm2rc.sample
  modules/FvwmConsole/FvwmConsoleC.pl.in
  modules/FvwmConsole/Makefile.am
Labels: area:doc, type:breaking

#382 Fix system.fvwm2rc not found
  fvwm/fvwm3.c
Labels: type:bug

#386 Remove explicit path to bson.h (closes #375)
  fvwm/builtins.h
Labels: area:build, type:bug
