Repository fvwmorg/fvwm3, pull requests merged in 2021-06, with the labels that each got.

#514 Update FvwmCommand to allow multiple args.
  bin/FvwmCommand.in
Labels: type:bug

#515 Retire FvwmTile and FvwmCascade wrappers.
  doc/modules/FvwmRearrange.adoc
  modules/FvwmRearrange/FvwmRearrange.c
  modules/FvwmRearrange/Makefile.am
Labels: type:breaking

#517 configure: remove stale references to BUGADDR
  configure.ac
Labels: area:build

#520 Update manual for Echo/EchoFuncDefinition
  doc/fvwm3/fvwm3.adoc
Labels: area:doc

#521 Make SnapAttraction snap to edges of all monitors.
  fvwm/move_resize.c
Labels: type:bug

#525 RandR: support RandRFunc for screen changes
  doc/fvwm3/fvwm3.adoc
  fvwm/events.c
Labels: type:enhancement

#526 EWMH_GetWorkArea use monitor dimensions.
  fvwm/ewmh.c
Labels: type:bug

#528 Set base struts only for primary monitor in default-config.
  default-config/config
Labels: type:bug

#530 Make RightPanel use primary monitor dimensions.
  default-config/config
Labels: type:bug

#527 Change FvwmPager Logic for initial window size.
  default-config/config
  doc/modules/FvwmPager.adoc
  modules/FvwmPager/x_pager.c
Labels: type:bug

#531 Add a screen option to the Scroll command.
  doc/fvwm3/fvwm3.adoc
  fvwm/virtual.c
  modules/FvwmPager/x_pager.c
Labels: type:enhancement

#532 RandR: fix const correctness
  fvwm/events.c
Labels: skip:changelog

#534 placement: remove conditional
  fvwm/placement.c
Labels: skip:changelog

#535 Move: disable working area when screen given
  fvwm/move_resize.c
Labels: type:bug

#539 expand: add desk, pagex, pagey variables
  doc/fvwm3/fvwm3.adoc
  fvwm/expand.c
Labels: type:enhancement

#544 Fix compiler warnings in modules/FvwmScript/Instructions.c
  modules/FvwmScript/Instructions.c
Labels: type:bug

#546 Unmaximize: restore _NET_WM_STATE
  fvwm/move_resize.c
Labels: type:bug

#549 Fix set_vp_size_and_loc() for FvwmPager.
  modules/FvwmPager/x_pager.c
Labels: skip:changelog, type:bug

#552 Add icon for Run Command.
  default-config/config
  default-config/images/icons/run_arrow.png
Labels: type:enhancement

#557 Add local configuration file to the default-config.
  default-config/config
Labels: type:enhancement

#558 Add commands to configure the size/position window.
  dev-docs/PARSING.md
  doc/fvwm3/fvwm3.adoc
  fvwm/builtins.c
  fvwm/commands.h
  fvwm/functable.c
  fvwm/fvwm3.c
  fvwm/move_resize.c
  fvwm/placement.c
  fvwm/screen.h
Labels: type:breaking, type:enhancement

#556 GNOME: remove DO_IGNORE_GNOME_HINTS
  fvwm/window_flags.h
Labels: type:bug

#565 Cleanup FvwmScript manual page.
  doc/modules/FvwmScript.adoc
Labels: area:doc, type:bug

#566 Make default-config greyed colorset grey.
  default-config/config
Labels: type:bug

#567 Cleanup SetRCDefaults()
  fvwm/fvwm3.c
Labels: type:enhancement
