Repository fvwmorg/fvwm3, pull requests merged in 2021-01, with the labels that each got.

#400 move x11 headers out of config.h
  configure.ac
  libs/fvwm_x11.h
Labels: area:build

#406 LocaleCharset: initialise with font
  libs/Fft.c
Labels: type:bug

#415 FvwmPager: Fix division by zero
  modules/FvwmPager/x_pager.c
Labels: type:bug

#416 conditionals: add HasBorders/HasTitle
  doc/fvwm3/fvwm3.adoc
  fvwm/conditional.c
Labels: type:enhancement
