Repository fvwmorg/fvwm3, pull requests merged in 2021-05, with the labels that each got.

#481 style: few cleanps
  fvwm/focus.c
  fvwm/fvwm3.c
  fvwm/misc.c
  libs/Fft.c
  libs/FftInterface.h
  libs/Flocale.h
  libs/FlocaleCharset.c
  modules/FvwmForm/FvwmForm.c
  modules/FvwmForm/ReadXServer.c
  modules/FvwmPager/FvwmPager.c
  modules/FvwmPager/FvwmPager.h
Labels: skip:changelog

#487 IRC: move from Freenode -> Libera.chat
  .github/ISSUE_TEMPLATE/config.yml
  .github/workflows/ccpp.yml
  README.md
Labels: skip:changelog

#490 IRC Notifier: Switch Github Actions
  .github/workflows/ccpp.yml
  .github/workflows/issues.yml
Labels: skip:changelog

#493 Update manpages in default-config
  default-config/config
Labels: area:doc, type:bug

#494 Add some more generated files to .gitignore.
  .gitignore
Labels: skip:changelog

#497 IRC: update nicknames
  .github/workflows/ccpp.yml
  .github/workflows/issues.yml
Labels: skip:changelog

#495 Remove xpmroot link.
  bin/Makefile.am
  configure.ac
  doc/bin/fvwm-root.adoc
Labels: type:breaking

#496 Ensure make uninstall removes default-config links.
  Makefile.am
  default-config/Makefile.am
  modules/Makefile.am
Labels: type:bug

#504 Recapture: fix erroneous maximizing of windows
  fvwm/add_window.c
Labels: type:bug

#506 Improve runcmd in the default-config.
  default-config/config
Labels: type:enhancement

#452 DesktopConfiguration: introduce `shared` option
  dev-docs/DESKTOPS.md
  dev-docs/shareddesks
  doc/fvwm3/fvwm3.adoc
  fvwm/add_window.c
  fvwm/builtins.c
  fvwm/events.c
  fvwm/fvwm3.c
  fvwm/move_resize.c
  fvwm/placement.c
  fvwm/placement.h
  fvwm/virtual.c
  libs/FScreen.c
  libs/FScreen.h
Labels: type:new-feature

#507 libs: remove reference to Fft.h
  libs/Makefile.am
Labels: skip:changelog

#510 build: add CHANGELOG.md to dist
  Makefile.am
Labels: area:build
