Repository fvwmorg/fvwm3, pull requests merged in 2021-02, with the labels that each got.

#421 Fix file handle leak.
  fvwm/read.c
Labels: type:bug

#424 Correct menu error short option from `-t` to `-e`
  doc/bin/fvwm-menu-desktop.adoc
Labels: area:doc, type:bug

#426 Fix 22kb memory leak.
  fvwm/functions.c
Labels: type:bug

#434 Pager: don't restrict new_desk to monitor boundaries
  modules/FvwmPager/FvwmPager.c
Labels: type:bug

#439 Conditionals: add TitleAt{Top,Bottom,Left,Right}
  doc/fvwm3/fvwm3.adoc
  fvwm/conditional.c
Labels: type:enhancement

#444 fix with some pixels off for 3d buttons
  libs/Graphics.c
Labels: type:bug

#441 Only allocate a copy of style strings if requested.
  fvwm/style.c
Labels: type:bug

#450 perms: remove erroneous 644 -> 755
  fvwm/events.c
  fvwm/functions.c
  fvwm/modconf.c
  fvwm/read.c
  fvwm/style.c
Labels: skip:changelog

#451 Fix the pixel overflow problem and clean up the math.
  libs/Graphics.c
Labels: type:bug
