Repository fvwmorg/fvwm3, pull requests merged in 2021-07, with the labels that each got.

#570 Fix pass through binding logic.
  fvwm/bindings.c
Labels: type:bug

#577 FvwmButtons: Shrink windows when honoring Hints.
  modules/FvwmButtons/misc.c
Labels: type:breaking, type:bug

#579 expand: add prev_{desk,pagex,pagey}
  doc/fvwm3/fvwm3.adoc
  fvwm/expand.c
Labels: type:enhancement

#580 cJSON: harden NULL checks
  fvwm/builtins.c
  modules/FvwmMFL/FvwmMFL.c
Labels: skip:changelog

#581 Add force_icons_size kludge to .stalonetrayrc.
  default-config/.stalonetrayrc
Labels: type:bug

#587 gitignore: add FvwmPrompt binary
  .gitignore
Labels: area:build, skip:changelog

#586 Fix typo in manual page.
  doc/fvwm3/fvwm3.adoc
Labels: area:doc, skip:changelog

#588 Github: move changelog generation to release workflow
  .github/workflows/ccpp.yml
  .github/workflows/release.yml
Labels: skip:changelog

#593 Bugfix: fvwm-menu-desktop --get-menus
  bin/fvwm-menu-desktop.in
Labels: type:bug
