Repository fvwmorg/fvwm3, pull requests merged in 2022-11, with the labels that each got.

#742 Update Move shuffle logic to jump to next monitor
  doc/fvwm3_manpage_source.adoc
  fvwm/move_resize.c
Labels: type:enhancement

#743 MWMBorder: fix calculation
  fvwm/borders.c
Labels: type:bug

#747 Don't set border colorsets by default.
  fvwm/ConfigFvwmDefaults
  fvwm/style.c
Labels: relates:decors

#745 style: silence warning for unconsumed string
  fvwm/style.c
Labels: type:bug

#746 conditional: screen: simplify logic
  fvwm/conditional.c
Labels: type:enhancement

#756 FvwmPager make mini windows always round down.
  modules/FvwmPager/x_pager.c
Labels: type:bug

#762 Allow SidePic in default-config.
  default-config/config
Labels: type:enhancement

#765 borders: treat 0 pixels as 1 pixel border
  libs/Graphics.c
Labels: type:bug

#767 Move shuffle, ensure window inside working area.
  fvwm/move_resize.c
Labels: type:enhancement
