Repository fvwmorg/fvwm3, pull requests merged in 2022-10, with the labels that each got.

#713 Rename .stalonetrayrc to stalonetrayrc
  default-config/Makefile.am
  default-config/config
  default-config/stalonetrayrc
Labels: type:bug

#714 Fix background resetting in default-config
  default-config/config
Labels: type:bug

#725 FvwmScript.c: fix wrong size of TabCom array
  modules/FvwmScript/FvwmScript.c
Labels: type:bug

#727 gotodesk: simplify logic for shared/global
  fvwm/virtual.c
Labels: type:bug

#730 decor: allow window borders separate colours
  doc/fvwm3_manpage_source.adoc
  fvwm/borders.c
  fvwm/fvwm.h
  fvwm/fvwm3.c
  fvwm/screen.h
  fvwm/style.c
  fvwm/style.h
Labels: type:new-feature, relates:decors

#731 remove fvwm-config
  .gitignore
  bin/Makefile.am
  configure.ac
  default-config/config
  doc/fvwm-config.adoc
  doc/fvwm3_manpage_source.adoc
  perllib/FVWM/Module.pm.in
Labels: type:breaking

#734 CI: update to latest IRC-message runner
  .github/workflows/ccpp.yml
  .github/workflows/issues.yml
Labels: skip:changelog

#738 deprecate color commands
  doc/fvwm3_manpage_source.adoc
  fvwm/fvwm.h
  fvwm/style.c
  fvwm/style.h
Labels: type:breaking

#739 docs: remove obsolete GNOME references
  doc/fvwm3_manpage_source.adoc
Labels: needs:info, area:doc
