Repository fvwmorg/fvwm3, pull requests merged in 2022-09, with the labels that each got.

#689 desk_add: fix starting desk/monitor
  fvwm/virtual.c
Labels: type:bug

#687 shared: fix flagging of new_desk
  fvwm/virtual.c
Labels: type:bug

#696 Add AnyScreen to conditional in IconManClick
  default-config/config
Labels: type:enhancement

#699 expand: add monitor.prev variable
  doc/fvwm3_manpage_source.adoc
  fvwm/events.c
  fvwm/expand.c
  libs/FScreen.c
  libs/FScreen.h
Labels: type:enhancement

#700 doc: don't build FvwmConsole.1 if FvwmPrompt enabled
  doc/Makefile.am
Labels: type:bug, area:doc

#697 DesktopConfiguration shared: keep windows in-situ
  fvwm/add_window.c
  fvwm/placement.c
  fvwm/virtual.c
  libs/FScreen.h
Labels: type:bug

#702 debug: tidy-up
  fvwm/virtual.c
Labels: skip:changelog

#703 MapRequest: don't fake map/unmap events
  fvwm/events.c
Labels: type:breaking

#706 github: release: tweak automation script
  .github/workflows/release.yml
Labels: skip:changelog, area:build

#707 release/1.0.5
  CHANGELOG.md
  configure.ac
Labels: skip:changelog

#708 doc: add missing manpage_source
  doc/Makefile.am
Labels: skip:changelog

#709 Working on 1.0.6
  configure.ac
Labels: skip:changelog

#712 doc: don't install fvwm3_manpage_source
  doc/Makefile.am
Labels: type:bug, area:doc
