Repository fvwmorg/fvwm3, pull requests merged in 2023-07, with the labels that each got.

#862 fonts: don't fallback to iconv using XFT
  fvwm/ewmh_names.c
Labels: type:bug

#856 FvwmPager: monitor config: skip whitespace
  modules/FvwmPager/FvwmPager.c
Labels: type:bug, relates:module

#864 CI: master -> main
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/ccpp.yml
  .github/workflows/release.yml
Labels: skip:changelog, area:build

#863 cJSON: update to v1.7.16
  libs/cJSON.c
  libs/cJSON.h
Labels: type:enhancement

#866 set next version
  configure.ac
Labels: skip:changelog

#870 FvwmScript: fix rendering of checkboxes
  modules/FvwmScript/Widgets/CheckBox.c
Labels: type:bug, relates:module

#869 SnapAttraction: honor all tokens mentioned in the manpage
  fvwm/move_resize.c
Labels: type:bug
