Repository fvwmorg/fvwm3, pull requests merged in 2023-09, with the labels that each got.

#888 sizehints: tighten check
  fvwm/events.c
Labels: type:bug

#887 CursorStyle: fix panframe cursors
  fvwm/cursor.c
Labels: type:bug

#886 FvwmPager: add fpmonitor impls for widths/heights
  modules/FvwmPager/FvwmPager.c
  modules/FvwmPager/FvwmPager.h
  modules/FvwmPager/x_pager.c
Labels: type:bug, relates:module

#901 MaskUsedModifiers: remove bits used for XKB group index
  fvwm/bindings.c
  libs/defaults.h
Labels: type:bug

#903 set next version
  configure.ac
Labels: skip:changelog

#908 Infostore: guard against UAF
  fvwm/infostore.c
Labels: type:bug

#907 recapture: fix incorrect handling of InitialState
  fvwm/session.c
Labels: type:bug

#909 Simplify _NET_WM_NAME setting
  fvwm/ewmh.c
Labels: type:bug
