Repository fvwmorg/fvwm3, pull requests merged in 2023-01, with the labels that each got.

#790 Updates to FvwmPager scaling math to improve visual aspects due to rounding errors.
  modules/FvwmPager/x_pager.c
Labels: type:enhancement

#799 workflow: automate release process
  .github/release.yml
  .github/workflows/release.yml
  mkrelease.sh
Labels: skip:changelog

#800 FvwmIconMan: fix segfault in initialisation
  modules/FvwmIconMan/x.c
Labels: type:bug

#801 randr: quit when no screens found & not active
  libs/FScreen.c
Labels: type:bug

#804 Working on 1.0.7
  configure.ac
Labels: skip:changelog

#806 dist: doc: include all doc sources
  doc/Makefile.am
Labels: type:bug, area:doc

#808 ver: back to 1.0.7
  configure.ac
Labels: skip:changelog

#815 code: rename functions with two underscores
  fvwm/add_window.c
  fvwm/bindings.c
  fvwm/builtins.c
  fvwm/conditional.c
  fvwm/decorations.c
  fvwm/events.c
  fvwm/execcontext.c
  fvwm/expand.c
  fvwm/focus.c
  fvwm/frame.c
  fvwm/functions.c
  fvwm/functions.h
  fvwm/geometry.c
  fvwm/menubindings.c
  fvwm/menus.c
  fvwm/modconf.c
  fvwm/module_interface.c
  fvwm/move_resize.c
  fvwm/move_resize.h
  fvwm/placement.c
  fvwm/stack.c
  fvwm/style.c
  fvwm/virtual.c
  libs/Bindings.c
  libs/FTips.c
  libs/gravity.c
Labels: type:enhancement
