Repository fvwmorg/fvwm3, pull requests merged in 2023-12, with the labels that each got.

#927 expand: fix $[monitor.0.XX] case
  fvwm/expand.c
Labels: type:bug

#911 WIP: MacOS Support
  configure.ac
  libs/Makefile.am
  modules/FvwmMFL/FvwmMFL.c
  modules/FvwmMFL/Makefile.am
Labels: type:enhancement

#931 build: set next version
  configure.ac
Labels: skip:changelog

#936 randr: fix primary flag check
  libs/FScreen.c
Labels: type:bug

#889 monitor: fix geometry parsing for window assignment
  fvwm/update.c
Labels: type:bug

#938 Add CurrentAtEnd to Alt-Tab WindowList
  default-config/config
Labels: type:enhancement

#939 Add DesktopNames to xdg desktop file.
  contrib/xsession/fvwm3.desktop.in
Labels: type:enhancement, relates:desktop
