Repository fvwmorg/fvwm3, pull requests merged in 2024-10, with the labels that each got.

#1061 librsvg: update to newer API
  libs/PictureImageLoader.c
Labels: type:bug, difficulty:easy, difficulty:gfi

#1063 Rename fvwm3.LL_CC.po files to LL_CC.po.
  po/README.md
  po/ar.po
  po/da.po
  po/de.po
  po/es.po
  po/fr.po
  po/fvwmpo.sh
  po/ru.po
  po/sv_SE.po
  po/zh_CN.po
  po/zh_TW.po
Labels: area:build

#1066 Tweak close vector button in default-config.
  default-config/config
Labels: type:enhancement, relates:decors

#1067 Adjust windows to fit working area after move.
  doc/fvwm3_manpage_source.adoc
  fvwm/ewmh.c
  fvwm/ewmh.h
  fvwm/move_resize.c
  fvwm/placement.c
Labels: relates:desktop, relates:ewmh

#1070 FvwmPager: Honor ewmh working area and option to ignore working area.
  doc/FvwmPager.adoc
  modules/FvwmPager/FvwmPager.c
  modules/FvwmPager/FvwmPager.h
  modules/FvwmPager/init_pager.c
  modules/FvwmPager/x_pager.c
Labels: type:enhancement, relates:module

#1072 FindScreenOfXY: Return closest monitor in dead area.
  libs/FScreen.c
Labels: type:enhancement

#1071 default-config: Don't close terminal if manpage not found.
  default-config/config
  po/fvwm3.pot
Labels: area:doc

#1074 ConfigWinPacket: no longer send monitor_name
  fvwm/module_interface.c
  libs/vpacket.h
  modules/FvwmIconMan/fvwm.c
Labels: type:bug

#1075 CONFIGARGS: reduce field count by one
  fvwm/module_interface.c
Labels: skip:changelog

#1079 Update POFILES in autotools.
  acinclude.m4
Labels: area:build

#1076 Fix issue with placement in per-monitor configuration.
  fvwm/add_window.c
Labels: type:bug, relates:placement

#1069 Improve monitor event handling
  fvwm/events.c
  libs/FScreen.c
  libs/FScreen.h
Labels: type:enhancement

#1084 Update editorconfig for EOF Newlines
  .editorconfig
  dev-docs/INSTALL.md
  doc/meson.build
  fvwm/events.c
  fvwm/module_interface.c
  libs/FScreen.c
  meson-scripts/dist-tarball.sh
  meson.build
Labels: area:build

#1086 meson: fix defines
  meson.build
Labels: area:build

#1085 Add Maximize keepgrowing flag.
  doc/fvwm3_manpage_source.adoc
  fvwm/move_resize.c
Labels: type:enhancement, relates:placement

#1090 PrintInfo: fix output of 'bindings'
  fvwm/bindings.c
Labels: type:bug

#1091 PrintInfo: don't clobber window-bindings
  fvwm/bindings.c
Labels: type:bug, skip:changelog

#1094 PrintInfo: bindings: reduce duplication
  fvwm/bindings.c
Labels: type:bug, skip:changelog

#1097 Fix CursorMove by more than one page in y-direction.
  fvwm/builtins.c
Labels: type:bug

#1098 Add XFixes support and CusorBarrier command.
  doc/fvwm3_manpage_source.adoc
  fvwm/commands.h
  fvwm/cursor.c
  fvwm/functable.c
  fvwm/fvwm3.c
  meson.build
  meson.options
Labels: type:new-feature
