Repository fvwmorg/fvwm3, pull requests merged in 2024-12, with the labels that each got.

#1129 FvwmPager: Update current desk correctly during init.
  modules/FvwmPager/messages.c
Labels: relates:module

#1135 SVG: set default width/height if absent
  libs/PictureImageLoader.c
Labels: type:bug

#1140 build: SVG: remove superflous includes
  libs/PictureImageLoader.c
Labels: area:build

#1141 man: Fix formatting in Style definition
  doc/fvwm3_manpage_source.adoc
Labels: area:doc

#1145 swapped mandoc and htmldoc options
  dev-docs/INSTALL.md
Labels: skip:changelog, area:doc

#1148 FvwmPrompt: honour "quit" as case-sensitive
  bin/FvwmPrompt/FvwmPrompt.go
Labels: type:enhancement, type:internal-improvement

#1151 FvwmPager: increase command stack size
  modules/FvwmPager/x_pager.c
Labels: type:internal-improvement

#1152 CI: release: consider internal-improvements
  .github/release.yml
Labels: skip:changelog, type:internal-improvement

#1153 WindowList missing options in man pages
  doc/fvwm3_manpage_source.adoc
Labels: area:doc

#1154 doc: fix spacing of options to WindowList
  doc/fvwm3_manpage_source.adoc
Labels: area:doc

#1156 Correct shadows on vertical titlebars
  libs/Graphics.c
Labels: type:bug, relates:decors
