Repository fvwmorg/fvwm3, pull requests merged in 2024-03, with the labels that each got.

#956 build: fix Xft/Freetype/Fontconfig check
  configure.ac
  dev-docs/INSTALL.md
Labels: type:breaking, area:build

#961 FvwmPager: use monitors from fvwm3lib
  fvwm/module_interface.c
  modules/FvwmPager/FvwmPager.c
  modules/FvwmPager/FvwmPager.h
  modules/FvwmPager/x_pager.c
Labels: relates:module

#962 FvwmPager: remove debug
  modules/FvwmPager/FvwmPager.c
Labels: relates:module

#964 FvwmPager: remove list_focus handling
  modules/FvwmPager/FvwmPager.c
Labels: type:bug, relates:module

#967 Goto{Desk,Page,DeskAndPage}: use 'screen' keyword
  fvwm/virtual.c
  modules/FvwmPager/x_pager.c
Labels: type:breaking

#963 Improve RandR Detection
  fvwm/events.c
  fvwm/ewmh.c
  libs/FScreen.c
  libs/FScreen.h
Labels: type:bug

#973 Stop fvwm-menu-desktop from informing users it cannot find icon %s.
  bin/fvwm-menu-desktop.in
Labels: type:bug

#976 shared mode: fix internal commands
  fvwm/move_resize.c
  fvwm/virtual.c
Labels: type:bug
