Repository fvwmorg/fvwm3, pull requests merged in 2024-08, with the labels that each got.

#1051 delete -D cli argument from usage, no longer valid
  fvwm/fvwm3.c
Labels: type:bug

#1047 Fix Restart functionality (after removal of single screen support)
  fvwm/session.c
Labels: type:bug

#1057 FvwmMFL: fix singletion/locking mechanism
  modules/FvwmMFL/FvwmMFL.c
Labels: relates:module

#1058 FvwmMFL: ignore SIGUSR2
  modules/FvwmMFL/FvwmMFL.c
Labels: type:bug, relates:module
