Repository fvwmorg/fvwm3, pull requests merged in 2024-11, with the labels that each got.

#1096 IconMan: suppress `-Wformat-overflow=`
  modules/FvwmIconMan/winlist.c
Labels: skip:changelog, area:build

#1099 Make xkbcommon required in meson.
  dev-docs/INSTALL.md
  meson.build
  meson.options
Labels: area:build

#1103 configargsnew: fix module packet
  fvwm/module_interface.c
Labels: type:bug

#1104 add_window: force style lookup
  fvwm/add_window.c
Labels: type:bug

#1108 Escape <= to keep asciidoctor from turning into an arrow.
  doc/fvwm3_manpage_source.adoc
Labels: area:doc

#1110 Manual page fix: Include GotoDesk screen RANDRNAME.
  doc/fvwm3_manpage_source.adoc
Labels: area:doc

#1113 Convert InfoStore to TAILQ.
  fvwm/infostore.c
  fvwm/infostore.h
  fvwm/session.c
Labels: type:enhancement

#1111 FvwmEvent - Remove FvwmAudio compatibility.
  doc/FvwmEvent.adoc
  modules/FvwmEvent/FvwmEvent.c
Labels: type:breaking, relates:module

#1115 infostore: move non-error case out of error block
  fvwm/infostore.c
Labels: type:bug

#1120 get_page_arguments: remove fw field
  fvwm/move_resize.c
  fvwm/virtual.c
  fvwm/virtual.h
Labels: type:internal-improvement

#1121 SetEnv: disallow '=' in envvar
  fvwm/builtins.c
Labels: type:bug

#1123 Move shuffle and Maximize grow all_windows and both_sides options.
  doc/fvwm3_manpage_source.adoc
  fvwm/move_resize.c
Labels: type:enhancement

#1124 GetDeskNumber fix, cleanup, and drop support for negative desks.
  doc/fvwm3_manpage_source.adoc
  fvwm/virtual.c
Labels: type:bug

#1125 meson: add check for xtrans
  meson.build
Labels: area:build

#1128 build: set next version
  configure.ac
  meson.build
Labels: skip:changelog, area:build
