Repository fvwmorg/fvwm3, pull requests merged in 2024-04, with the labels that each got.

#989 Make desktop buttons bigger in RightPanel
  default-config/config
Labels: type:enhancement

#990 Don't use a declaration state in for loops
  modules/FvwmPager/FvwmPager.c
  modules/FvwmPager/x_pager.c
Labels: skip:changelog, area:build

#987 Use AX_COMPARE_VERSION macro for golang version checks
  acinclude.m4
  configure.ac
Labels: area:build

#988 Add math expansion variables.
  default-config/config
  doc/fvwm3_manpage_source.adoc
  fvwm/expand.c
Labels: type:enhancement

#991 configure: add go version to summary
  configure.ac
Labels: area:build

#994 Cleanup FvwmPager's window handling methods.
  modules/FvwmPager/FvwmPager.c
  modules/FvwmPager/FvwmPager.h
  modules/FvwmPager/x_pager.c
Labels: type:bug, relates:module

#1001 FvwmPager Bugfix: Fix UseSkipList
  modules/FvwmPager/x_pager.c
Labels: type:bug, skip:changelog, relates:module

#1002 FvwmPager: CurrentDeskPerMonitor and two other features.
  doc/FvwmPager.adoc
  modules/FvwmPager/FvwmPager.c
  modules/FvwmPager/FvwmPager.h
  modules/FvwmPager/x_pager.c
Labels: type:enhancement, relates:module

#1003 FvwmPager: New mode IsShared for DesktopConfiguration shared.
  doc/FvwmPager.adoc
  modules/FvwmPager/FvwmPager.c
  modules/FvwmPager/FvwmPager.h
  modules/FvwmPager/x_pager.c
Labels: type:enhancement, relates:module

#1005 cJSON: bump to 1.7.17
  libs/cJSON.c
  libs/cJSON.h
Labels: type:bug

#1012 EWMH Events: more _NET_WM_STATE client messages
  fvwm/ewmh_events.c
Labels: type:enhancement, relates:ewmh

#1017 FvwmPager: Make mouse bindings configurable.
  doc/FvwmPager.adoc
  modules/FvwmPager/FvwmPager.c
  modules/FvwmPager/FvwmPager.h
  modules/FvwmPager/init_pager.c
  modules/FvwmPager/x_pager.c
Labels: type:enhancement, relates:module

#1018 Maximize: don't change monitor when unmaximizing
  fvwm/move_resize.c
Labels: type:bug

#1020 FvwmPager: Use NULL not "" to avoid crashes on some systems.
  doc/FvwmPager.adoc
  modules/FvwmPager/init_pager.c
Labels: type:bug, relates:module

#1019 Send_ConfigInfo improvements
  fvwm/modconf.c
  fvwm/module_interface.c
  fvwm/module_interface.h
Labels: type:bug
