Repository fvwmorg/fvwm3, pull requests merged in 2025-02, with the labels that each got.

#1163 build: macos: ignore case-sensitive filename warnings
  meson.build
Labels: area:build

#1162 Style syntax matching: Class, Name, Resource, Icon, WindowID
  doc/fvwm3_manpage_source.adoc
  fvwm/builtins.c
  fvwm/fvwm.h
  fvwm/style.c
  fvwm/style.h
Labels: type:enhancement, type:breaking

#1166 build: set next version
  configure.ac
  meson.build
Labels: skip:changelog

#1170 FvwmRearrange: Use -on_screen to tile/cascade all windows on the monitor.
  doc/FvwmRearrange.adoc
  modules/FvwmRearrange/FvwmRearrange.c
Labels: type:enhancement, relates:module

#1174 build: macos: fix path to fribidi
  libs/BidiJoin.h
  libs/FBidi.c
Labels: area:build

#1177 fvwm-convert-2.6: fix syntax error
  bin/fvwm-convert-2.6.in
Labels: type:bug

#1179 FvwmRearrange: Add -win_cmd COMMAND option.
  doc/FvwmRearrange.adoc
  modules/FvwmRearrange/FvwmRearrange.c
Labels: type:enhancement, relates:module
