Repository fvwmorg/fvwm3, pull requests merged in 2025-01, with the labels that each got.

#1158 expand: introduce $[desk.count]
  doc/fvwm3_manpage_source.adoc
  fvwm/expand.c
  fvwm/virtual.c
  fvwm/virtual.h
Labels: type:enhancement

#1159 FvwmRerrange: Add gap option when tiling.
  doc/FvwmRearrange.adoc
  modules/FvwmRearrange/FvwmRearrange.c
Labels: type:enhancement, relates:module

#1161 ResizeMove: Make Warp imply WarpToWindow
  fvwm/move_resize.c
Labels: type:bug

#1118 Add screen option to CursorMove.
  doc/fvwm3_manpage_source.adoc
  fvwm/builtins.c
  fvwm/cursor.c
Labels: type:enhancement
